### ISSUE TITLE
Make Code Re-Generation Easier

### ISSUE THREAD

**Issue by lhannest** [STARInformatics/translator-knowledge-beacon#1]
There really should be three sub-projects, one for the server, one for the client (if the user wishes to have one), and one for the server implementation. That way, we can remove the --skip-overwrite flag from our script and allow for overwriting the server project each time we re-generate the code. Then, just plug the server implementation call back into the ControllerApi classes.

We should encourage users to do this (in our documentation), and do this ourselves (in our private implementation).

**Comment by goodb** [comment]
I suggest that - for the java client/server code that you need anyway to drive the tkbio app you just go ahead and commit it to the repo.  That will be the fastest way to get a java developer going.  When the API spec changes, then you execute the code generation, commit and test.  That way the dev has nothing to do but fill in the business logic which is what you want for beacon provider.  The code should also have test cases ready.  It seems unnecessarily complex right now.

**Comment by goodb** [comment]
Moved to https://github.com/NCATS-Tangerine/translator-knowledge-beacon/issues/1
