### ISSUE TITLE
Create a federated query client

### ISSUE THREAD

**Issue by cmungall** [STARInformatics/translator-knowledge-beacon#11]
We are exploring architectures such as linked data fragments to be able to support queries involving joins across k-beacons. We realize that this may be massively inefficient at first, but that is fine for demoing purposes

**Comment by cmungall** [comment]
@balhoff has implemented a demo of LDFs wrapping k-beacons: https://github.com/balhoff/beacon-tpf

**Comment by goodb** [comment]
moved to https://github.com/NCATS-Tangerine/translator-knowledge-beacon/issues/7
