### ISSUE TITLE
Expand evidence and provenance model

### ISSUE THREAD

**Issue by cmungall** [STARInformatics/translator-knowledge-beacon#6]
Separate reference (e.g. pmid), evidence type (e.g. ECO), source (i.e. database from which it was extracted)

**Comment by cmungall** [comment]
Steve showed an example of using the prov model: https://github.com/NCATS-Tangerine/cq-notebooks/tree/master/GreenTeamQ1_Asthma_Outcomes_PM2.5_Ozone_Exposures

**Comment by goodb** [comment]
moved to https://github.com/NCATS-Tangerine/translator-knowledge-beacon/issues/4
